"""worker + chief-worker realtions tables

Revision ID: 95eeca19f29d
Revises: 
Create Date: 2021-08-23 12:12:34.957860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95eeca19f29d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chief_worker_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chief_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('second_name', sa.String(length=64), nullable=True),
    sa.Column('patronymic', sa.String(length=64), nullable=True),
    sa.Column('works_from_date', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('is_chief', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker')
    op.drop_table('chief_worker_relations')
    # ### end Alembic commands ###
